spring.application.name=tfg

# ========================================
# Configuración de H2 para Desarrollo
# ========================================

# Activar consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

# JPA / Hibernate con H2
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

# No ejecutar scripts SQL externos (defer importante para que no se ejecuten los inserts antes de crear la DB)
spring.jpa.defer-datasource-initialization=true 
spring.sql.init.mode=embedded

# ========================================
# Configuración de Thymeleaf
# ========================================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
